# Generated by Django 4.1.7 on 2023-04-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0009_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='mensaje',
            field=models.CharField(default='a', max_length=150),
            preserve_default=False,
        ),
    ]
