# Generated by Django 4.1.7 on 2023-04-09 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0010_contacto_mensaje'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
